-- =====================================================================
-- 059 - Backfill certificate issuance requests for completed courses
-- =====================================================================
-- WHY:
--   Some academy course enrollments reached 100% progress while their
--   `status` stayed 'active' (never flipped to 'COMPLETED'), so the
--   completion trigger that creates a certificate request never fired.
--   As a result those students see an empty "شهاداتي" page.
--
-- WHAT THIS DOES (idempotent, safe to re-run):
--   1. Marks any academy course enrollment with progress >= 100 as
--      'COMPLETED' so data stays consistent and future triggers work.
--   2. Creates a 'submitted' certificate_issuance_request for every such
--      completed enrollment that does NOT already have one — mirroring
--      exactly what the app's createEligibilityRequest(kind='course',
--      skipDataStep=true) does: status 'submitted', default active
--      academy template, language 'ar'.
--
-- NOTE: this only creates the REQUEST. The PDF itself is generated by the
--   app (autoIssueRequest) the next time the student opens the
--   certificates page, or when an admin issues it. No email is hardcoded;
--   this fixes the issue for every affected student at once.
-- =====================================================================

BEGIN;

-- 1. Normalise enrollment status for fully-completed courses.
UPDATE enrollments
SET status = 'COMPLETED'
WHERE progress_percentage >= 100
  AND status <> 'COMPLETED';

-- 2. Create missing 'submitted' requests for completed academy courses.
INSERT INTO certificate_issuance_requests (
  scope, kind, student_id, source_table, source_id, source_label,
  template_id, language, status, requested_at, submitted_at
)
SELECT
  'academy'                              AS scope,
  'course'                               AS kind,
  e.student_id,
  'courses'                              AS source_table,
  e.course_id                            AS source_id,
  c.title                                AS source_label,
  -- Course-specific template override → otherwise the default active
  -- academy template (matches resolveDefaultTemplate's fallback).
  COALESCE(
    c.certificate_template_id,
    (SELECT id FROM certificate_templates
       WHERE scope = 'academy' AND is_active = TRUE
       ORDER BY is_default DESC, created_at DESC
       LIMIT 1)
  )                                      AS template_id,
  'ar'                                   AS language,
  'submitted'                            AS status,
  NOW()                                  AS requested_at,
  NOW()                                  AS submitted_at
FROM enrollments e
JOIN courses c ON c.id = e.course_id
WHERE e.progress_percentage >= 100
  AND COALESCE(c.certificate_enabled, TRUE) = TRUE
  AND NOT EXISTS (
    SELECT 1 FROM certificate_issuance_requests r
    WHERE r.student_id = e.student_id
      AND r.scope = 'academy'
      AND r.kind = 'course'
      AND r.source_table = 'courses'
      AND r.source_id = e.course_id
  );

COMMIT;

-- 3. Verify (read-only): show the requests that now exist for completed courses.
SELECT r.id, r.student_id, r.source_label, r.status, r.template_id, r.created_at
FROM certificate_issuance_requests r
WHERE r.scope = 'academy' AND r.kind = 'course'
ORDER BY r.created_at DESC
LIMIT 50;
