WITH expected(table_name, column_name, used_in) AS (
  VALUES
    ('user_points',            'user_id',                 'gamification.awardPoints'),
    ('user_points',            'total_points',            'gamification.awardPoints / leaderboard'),
    ('user_points',            'level',                   'gamification / leaderboard'),
    ('user_points',            'streak_days',             'gamification.recomputeStreak'),
    ('user_points',            'longest_streak',          'gamification.recomputeStreak'),
    ('user_points',            'last_activity_date',      'gamification.recomputeStreak'),
    ('points_log',             'user_id',                 'gamification.awardPoints'),
    ('points_log',             'points',                  'gamification.awardPoints'),
    ('points_log',             'reason',                  'gamification.awardPoints'),
    ('points_log',             'description',             'gamification.awardPoints'),
    ('points_log',             'related_entity_type',     'gamification.awardPoints'),
    ('points_log',             'related_entity_id',       'gamification.awardPoints'),
    ('points_log',             'created_at',              'student/points API + leaderboard'),
    ('badges',                 'user_id',                 'student/badges API'),
    ('badges',                 'badge_type',              'gamification.checkAndAwardBadges'),
    ('badges',                 'badge_name',              'gamification.checkAndAwardBadges'),
    ('badges',                 'badge_description',       'gamification.checkAndAwardBadges'),
    ('badges',                 'badge_icon_url',          'gamification.checkAndAwardBadges'),
    ('badges',                 'points_awarded',          'gamification.checkAndAwardBadges'),
    ('badges',                 'awarded_at',              'student/badges API'),
    ('fiqh_questions',         'asked_by',                'admin/fiqh GET'),
    ('fiqh_questions',         'answered_by',             'admin/fiqh PATCH'),
    ('fiqh_questions',         'is_published',            'admin/fiqh GET + PATCH'),
    ('fiqh_questions',         'category',                'admin/fiqh GET filter'),
    ('fiqh_questions',         'is_anonymous',            'admin/fiqh GET'),
    ('fiqh_questions',         'asked_at',                'admin/fiqh GET'),
    ('fiqh_questions',         'answered_at',             'admin/fiqh PATCH'),
    ('academy_teachers',       'user_id',                 'supervisor/teachers GET'),
    ('academy_teachers',       'is_verified',             'supervisor/teachers GET'),
    ('academy_teachers',       'verified_by',             'supervisor/teachers PATCH'),
    ('academy_teachers',       'verified_at',             'supervisor/teachers PATCH'),
    ('academy_teachers',       'trust_score',             'supervisor/teachers GET'),
    ('academy_teachers',       'specialization',          'supervisor/teachers GET'),
    ('academy_teachers',       'years_experience',        'supervisor/teachers GET'),
    ('academy_teachers',       'certifications',          'supervisor/teachers GET'),
    ('teacher_verifications',  'teacher_user_id',         'supervisor/teachers PATCH'),
    ('teacher_verifications',  'supervisor_id',           'supervisor/teachers PATCH'),
    ('teacher_verifications',  'action',                  'supervisor/teachers PATCH'),
    ('teacher_verifications',  'notes',                   'supervisor/teachers PATCH'),
    ('teacher_verifications',  'created_at',              'supervisor/teachers PATCH'),
    ('supervisor_assignments', 'supervisor_id',           'supervisor scope'),
    ('tasks',                  'points_reward',           'grade route awardTaskPoints'),
    ('tasks',                  'max_score',               'grade route'),
    ('tasks',                  'course_id',               'grade route ownership'),
    ('task_submissions',       'student_id',              'grade route'),
    ('task_submissions',       'task_id',                 'grade route'),
    ('task_submissions',       'score',                   'grade route'),
    ('live_sessions',          'course_id',               'sessions/[id]/attend'),
    ('session_attendance',     'session_id',              'sessions/[id]/attend'),
    ('session_attendance',     'student_id',              'sessions/[id]/attend'),
    ('session_attendance',     'joined_at',               'sessions/[id]/attend'),
    ('enrollments',            'student_id',              'sessions/attend ownership'),
    ('enrollments',            'course_id',               'sessions/attend ownership'),
    ('enrollments',            'status',                  'sessions/attend ownership'),
    ('users',                  'role',                    'all session checks'),
    ('users',                  'name',                    'admin/fiqh + supervisor list'),
    ('users',                  'avatar_url',              'admin/fiqh + supervisor list'),
    ('users',                  'email',                   'supervisor list')
)
SELECT
  e.table_name,
  e.column_name,
  e.used_in,
  CASE WHEN c.column_name IS NULL THEN 'MISSING' ELSE 'OK' END AS status,
  c.data_type
FROM expected e
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public'
 AND c.table_name   = e.table_name
 AND c.column_name  = e.column_name
ORDER BY status DESC, e.table_name, e.column_name;
