export type DocsLocale = 'ar' | 'en'

export type LocalizedText = Record<DocsLocale, string>

export type DocsSection = {
  id: string
  title: LocalizedText
  intro?: LocalizedText
  steps: Record<DocsLocale, string[]>
  note?: LocalizedText
}

export type DocsGuide = {
  slug: string
  group: 'start' | 'users' | 'staff' | 'admin' | 'support'
  icon: 'start' | 'student' | 'reader' | 'teacher' | 'parent' | 'supervisor' | 'admin' | 'support'
  title: LocalizedText
  description: LocalizedText
  audience: LocalizedText
  keywords: Record<DocsLocale, string[]>
  productRoutes: string[]
  reviewedAt: string
  sections: DocsSection[]
}

export const docsGroups: Array<{ id: DocsGuide['group']; label: LocalizedText }> = [
  { id: 'start', label: { ar: 'ابدأ هنا', en: 'Start here' } },
  { id: 'users', label: { ar: 'أدلة المستخدمين', en: 'User guides' } },
  { id: 'staff', label: { ar: 'المعلمون والمشرفون', en: 'Staff & supervisors' } },
  { id: 'admin', label: { ar: 'أدلة الإدارة', en: 'Administration' } },
  { id: 'support', label: { ar: 'المساعدة', en: 'Help & support' } },
]

export const docsGuides: DocsGuide[] = [
  {
    slug: 'getting-started', group: 'start', icon: 'start', reviewedAt: '2026-07-21',
    title: { ar: 'إنشاء الحساب والبدء', en: 'Create an account and get started' },
    description: { ar: 'من إنشاء حسابك وحتى الوصول إلى لوحة التحكم المناسبة لدورك.', en: 'From creating your account to reaching the dashboard for your role.' },
    audience: { ar: 'جميع الزوار والمستخدمين الجدد', en: 'All visitors and new users' },
    keywords: { ar: ['تسجيل', 'حساب', 'دخول', 'كلمة المرور', 'تحقق'], en: ['register', 'account', 'login', 'password', 'verify'] },
    productRoutes: ['/register', '/reader-register', '/teacher-register', '/verify', '/login', '/forgot-password'],
    sections: [
      { id: 'choose-account', title: { ar: 'اختر نوع الحساب', en: 'Choose your account type' }, intro: { ar: 'اختيار النوع الصحيح يحدد نموذج التسجيل ومسار الموافقة.', en: 'Your account type determines the registration form and approval flow.' }, steps: { ar: ['اختر حساب طالب للتعلم، حضور الحلقات، وإرسال التلاوات.', 'اختر طلب مقرئ إذا كنت تريد مراجعة تلاوات الطلاب وإدارة جلسات التسميع.', 'اختر طلب معلم إذا كنت ستدير دورات الأكاديمية ودروسها.', 'حسابات الإدارة والإشراف تُمنح بواسطة الإدارة ولا تُنشأ من نموذج التسجيل العام.'], en: ['Choose Student to learn, join circles, and submit recitations.', 'Choose Reader application to review recitations and manage recitation sessions.', 'Choose Teacher application to manage academy courses and lessons.', 'Administration and supervisor access is assigned by management, not through public registration.'] } },
      { id: 'register', title: { ar: 'سجّل حسابًا', en: 'Register your account' }, steps: { ar: ['افتح صفحة التسجيل المناسبة.', 'أدخل بياناتك الصحيحة وبريدًا يمكنك الوصول إليه.', 'أنشئ كلمة مرور قوية، وافق على الشروط، ثم أرسل النموذج.', 'أدخل رمز التحقق الذي يصلك. إذا انتهت صلاحيته، اطلب رمزًا جديدًا من شاشة التحقق.'], en: ['Open the registration page for your account type.', 'Enter accurate information and an email address you can access.', 'Create a strong password, accept the terms, and submit.', 'Enter the verification code you receive. Request a new code if it expires.'] }, note: { ar: 'طلبات المقرئ والمعلم قد تبقى قيد المراجعة قبل تفعيل أدوات الدور.', en: 'Reader and teacher applications may remain under review before role tools are enabled.' } },
      { id: 'login', title: { ar: 'الدخول واستعادة الحساب', en: 'Sign in and recover access' }, steps: { ar: ['افتح تسجيل الدخول وأدخل البريد وكلمة المرور.', 'بعد الدخول ستنتقل إلى اللوحة المتاحة حسب دورك وصلاحياتك.', 'إذا نسيت كلمة المرور، اختر نسيت كلمة المرور واتبع رسالة الاستعادة.', 'إذا ظهرت رسالة انتظار أو رفض، راجع حالة طلب الدور أو تواصل مع الدعم.'], en: ['Open Sign in and enter your email and password.', 'You will be sent to the dashboard available for your role and permissions.', 'Use Forgot password and follow the recovery message if needed.', 'If you see pending or rejected status, review your role application or contact support.'] } },
    ],
  },
  {
    slug: 'student-guide', group: 'users', icon: 'student', reviewedAt: '2026-07-21',
    title: { ar: 'دليل الطالب', en: 'Student guide' },
    description: { ar: 'الدورات، التلاوات، الحلقات، الحجز، التقدم والمكافآت.', en: 'Courses, recitations, circles, booking, progress, and rewards.' },
    audience: { ar: 'طلاب المقرأة والأكاديمية', en: 'Maqraa and academy students' },
    keywords: { ar: ['طالب', 'دورة', 'شراء', 'التحاق', 'تلاوة', 'حلقة', 'واجب', 'شهادة'], en: ['student', 'course', 'purchase', 'enroll', 'recitation', 'circle', 'assignment', 'certificate'] },
    productRoutes: ['/student', '/student/submit', '/student/halaqat', '/student/booking', '/academy/student/courses'],
    sections: [
      { id: 'dashboard', title: { ar: 'استخدم لوحة الطالب', en: 'Use the student dashboard' }, steps: { ar: ['راجع الملخص لمعرفة مهامك والجلسات القادمة.', 'افتح الإشعارات لمعرفة التقييمات والقبول والتحديثات.', 'حدّث ملفك الشخصي وبيانات التواصل عند الحاجة.'], en: ['Review the summary for tasks and upcoming sessions.', 'Open notifications for reviews, approvals, and updates.', 'Keep your profile and contact details current.'] } },
      { id: 'courses', title: { ar: 'الالتحاق بدورة ودراسة الدروس', en: 'Enroll in a course and study lessons' }, steps: { ar: ['افتح الأكاديمية ثم استعرض الدورات المتاحة لك.', 'افتح صفحة الدورة واقرأ الوصف والمتطلبات قبل طلب الالتحاق.', 'اضغط زر الالتحاق أو الشراء الظاهر في صفحة الدورة؛ إذا كانت الدورة مدفوعة ستظهر لك خطوة الدفع المتاحة، وإلا يُسجل طلبك مباشرة.', 'بعد القبول، افتح دوراتي ثم اختر الدورة والدّرس المطلوب.', 'أكمل المحتوى والواجبات بالترتيب وتابع حالة التصحيح من صفحة مهامك.'], en: ['Open the Academy and browse courses available to you.', 'Open a course and review its description and requirements before enrolling.', 'Use the enrollment or purchase action shown on the course. Paid courses show the available payment step; otherwise your enrollment is recorded directly.', 'After approval, open My courses and choose the course and lesson.', 'Complete content and assignments in order, then track grading from your tasks.'] }, note: { ar: 'الأزرار المتاحة تعتمد على نشر الدورة، وصولك للأكاديمية، وحالة الالتحاق.', en: 'Available actions depend on course publication, academy access, and enrollment status.' } },
      { id: 'recitation', title: { ar: 'أرسل تلاوة وتابع تقييمها', en: 'Submit and track a recitation' }, steps: { ar: ['افتح إرسال تلاوة وحدد السورة ونطاق الآيات.', 'سجّل أو ارفع الملف الصوتي ثم راجع البيانات قبل الإرسال.', 'تابع الحالة من تلاواتي: قيد المراجعة، تحتاج مراجعة، متقنة، أو تحتاج جلسة.', 'افتح التلاوة لقراءة ملاحظات المقرئ، ثم أعد المحاولة أو احجز جلسة إذا طُلب ذلك.'], en: ['Open Submit recitation and select the surah and verse range.', 'Record or upload audio, then review the details before submitting.', 'Track it under My recitations: in review, needs review, mastered, or needs a session.', 'Open the recitation for reader feedback, then retry or book a session when requested.'] } },
      { id: 'circles', title: { ar: 'الحلقات والجلسات المباشرة', en: 'Circles and live sessions' }, steps: { ar: ['افتح الحلقات واختر الحلقة المسجل بها أو المتاحة للتقديم.', 'راجع الموعد والمقرئ والتعليمات.', 'عند بدء الموعد استخدم زر الانضمام للغرفة المباشرة.', 'تابع الحضور والتقدم من صفحات الجلسات والتقدم والتقويم.'], en: ['Open Circles and choose your enrolled circle or one open for application.', 'Review the schedule, reader, and instructions.', 'At the scheduled time, use Join to enter the live room.', 'Track attendance and progress from Sessions, Progress, and Calendar.'] } },
      { id: 'rewards', title: { ar: 'التقدم والشهادات والمكافآت', en: 'Progress, certificates, and rewards' }, steps: { ar: ['راجع مسارات الحفظ والتجويد لمعرفة المرحلة الحالية.', 'افتح النقاط والشارات لمعرفة الإنجازات وكيفية اكتسابها.', 'شارك في المسابقات المتاحة واقرأ الشروط قبل الانضمام.', 'عند استيفاء الشروط افتح الشهادات وقدّم الطلب أو نزّل الشهادة المتاحة.'], en: ['Review memorization and tajweed paths for your current stage.', 'Open Points and Badges to see achievements and how to earn them.', 'Join available competitions after reading their rules.', 'When eligible, open Certificates to request or download your certificate.'] } },
    ],
  },
  {
    slug: 'reader-guide', group: 'staff', icon: 'reader', reviewedAt: '2026-07-21',
    title: { ar: 'دليل المقرئ', en: 'Reader guide' }, description: { ar: 'اعتماد الحساب، مراجعة التلاوات، الطلاب والحلقات والجلسات.', en: 'Approval, recitation reviews, students, circles, and sessions.' }, audience: { ar: 'المقرئون المعتمدون والمتقدمون', en: 'Approved and applicant readers' }, keywords: { ar: ['مقرئ', 'تقييم', 'تلاوة', 'جلسة', 'حلقة'], en: ['reader', 'review', 'recitation', 'session', 'circle'] }, productRoutes: ['/reader-register', '/reader/recitations', '/reader/students', '/reader/halaqat', '/reader/schedule'],
    sections: [
      { id: 'approval', title: { ar: 'التقديم والاعتماد', en: 'Apply and get approved' }, steps: { ar: ['أرسل نموذج المقرئ مع المؤهلات والبيانات المطلوبة.', 'تحقق من بريدك ثم انتظر مراجعة الإدارة.', 'بعد القبول سجّل الدخول وأكمل ملفك وجدولك المتاح.'], en: ['Submit the reader form with required details and qualifications.', 'Verify your email and wait for management review.', 'After approval, sign in and complete your profile and availability.'] } },
      { id: 'reviews', title: { ar: 'راجع تلاوة طالب', en: 'Review a student recitation' }, steps: { ar: ['افتح قائمة التلاوات واختر طلبًا مسندًا إليك.', 'استمع للملف كاملًا وراجع السورة ونطاق الآيات.', 'أضف التقدير والملاحظات والوسوم المناسبة.', 'احفظ التقييم وحدد هل أتقن الطالب أم يحتاج مراجعة أو جلسة.'], en: ['Open Recitations and select an item assigned to you.', 'Listen fully and verify the surah and verse range.', 'Add the grade, feedback, and relevant tags.', 'Save and decide whether the student mastered it, needs review, or needs a session.'] } },
      { id: 'sessions', title: { ar: 'أدر الحلقات والجلسات', en: 'Manage circles and sessions' }, steps: { ar: ['راجع جدولك والطلاب وطلبات الالتحاق.', 'افتح الحلقة أو الجلسة لمعرفة الحضور والخطة.', 'ابدأ الغرفة المباشرة في موعدها وسجل ملاحظات الطالب.', 'حدّث النتيجة والتقدم بعد انتهاء الجلسة.'], en: ['Review your schedule, students, and enrollment requests.', 'Open a circle or session for attendance and plan details.', 'Start the live room on time and record student notes.', 'Update the result and progress after the session.'] } },
    ],
  },
  {
    slug: 'teacher-guide', group: 'staff', icon: 'teacher', reviewedAt: '2026-07-21',
    title: { ar: 'دليل المعلم', en: 'Teacher guide' }, description: { ar: 'إدارة دورات الأكاديمية والدروس والطلاب والواجبات والجلسات.', en: 'Manage academy courses, lessons, students, assignments, and sessions.' }, audience: { ar: 'معلمو الأكاديمية المعتمدون', en: 'Approved academy teachers' }, keywords: { ar: ['معلم', 'دورة', 'درس', 'واجب', 'تصحيح'], en: ['teacher', 'course', 'lesson', 'assignment', 'grading'] }, productRoutes: ['/teacher-register', '/teacher/courses', '/academy/teacher'],
    sections: [
      { id: 'course', title: { ar: 'أنشئ وأدر محتوى الدورة', en: 'Create and manage course content' }, steps: { ar: ['بعد اعتمادك افتح لوحة المعلم ثم الدورات.', 'أنشئ أو افتح الدورة المصرح لك بإدارتها.', 'أضف الوحدات والدروس والمواد بالترتيب الصحيح.', 'راجع المحتوى قبل النشر، ولا تنشر مسودة غير مكتملة.', 'تابع التسجيلات والطلاب من صفحة الدورة.'], en: ['After approval, open the teacher dashboard and Courses.', 'Create or open a course you are authorized to manage.', 'Add modules, lessons, and resources in the correct order.', 'Review everything before publishing.', 'Track enrollments and students from the course page.'] } },
      { id: 'assignments', title: { ar: 'الواجبات والتصحيح', en: 'Assignments and grading' }, steps: { ar: ['أنشئ الواجب داخل الدورة وحدد النوع والتعليمات والموعد.', 'راجع التسليمات من لوحة المهام.', 'افتح تسليم الطالب وأضف الدرجة والتغذية الراجعة.', 'احفظ التصحيح ليتلقى الطالب التحديث.'], en: ['Create an assignment with type, instructions, and deadline.', 'Review submissions from the tasks area.', 'Open a submission and add a grade and feedback.', 'Save the grade so the student receives the update.'] } },
      { id: 'live', title: { ar: 'الجلسات والتواصل', en: 'Sessions and communication' }, steps: { ar: ['جدول جلسة مرتبطة بالدورة أو الطالب وحدد وقتها.', 'ابدأ الجلسة المباشرة من صفحة الجلسة عند الموعد.', 'استخدم المحادثات والإشعارات للتواصل المتعلق بالدراسة.', 'سجل الحضور والنتيجة بعد الجلسة.'], en: ['Schedule a session for a course or student.', 'Start the live room from the session page at the scheduled time.', 'Use chats and notifications for study-related communication.', 'Record attendance and outcomes afterward.'] } },
    ],
  },
  {
    slug: 'parent-guide', group: 'users', icon: 'parent', reviewedAt: '2026-07-21',
    title: { ar: 'دليل ول�� الأمر', en: 'Parent guide' }, description: { ar: 'ربط الأبناء ومتابعة التقدم والطلبات والتواصل.', en: 'Link children and follow progress, requests, and communication.' }, audience: { ar: 'أولياء الأمور والحسابات العائلية', en: 'Parents and family accounts' }, keywords: { ar: ['ولي الأمر', 'ابن', 'عائلة', 'متابعة', 'موافقة'], en: ['parent', 'child', 'family', 'progress', 'approval'] }, productRoutes: ['/student/family', '/academy/parent'],
    sections: [
      { id: 'link', title: { ar: 'اربط حساب الابن', en: 'Link a child account' }, steps: { ar: ['افتح قسم العائلة أو الأبناء.', 'أرسل طلب الربط باستخدام البيانات المطلوبة.', 'انتظر موافقة الطرف الآخر أو الإدارة حسب نوع الطلب.', 'بعد الربط سيظهر الابن ضمن قائمة المتابعة.'], en: ['Open Family or Children.', 'Send a link request using the required details.', 'Wait for the other party or management to approve.', 'After approval, the child appears in your tracking list.'] } },
      { id: 'follow', title: { ar: 'تابع التقدم بأمان', en: 'Follow progress safely' }, steps: { ar: ['اختر الابن ثم راجع ملخص التقدم والتقويم.', 'راجع الحضور والواجبات والتقييمات المتاحة لك.', 'تابع الإشعارات والطلبات التي تحتاج موافقتك.', 'استخدم قناة الرسائل المخصصة عند الحاجة للتواصل.'], en: ['Choose a child and review progress and calendar.', 'Review attendance, assignments, and visible evaluations.', 'Follow notifications and requests that need your approval.', 'Use the designated messaging channel when communication is needed.'] } },
    ],
  },
  {
    slug: 'supervisor-guide', group: 'staff', icon: 'supervisor', reviewedAt: '2026-07-21',
    title: { ar: 'دليل المشرفين', en: 'Supervisor guide' }, description: { ar: 'دليل نطاقات إشراف الطلاب والمقرئين والمحتوى والفقه والجودة.', en: 'Scopes for student, reader, content, fiqh, and quality supervision.' }, audience: { ar: 'جميع رتب الإشراف', en: 'All supervisor roles' }, keywords: { ar: ['مشرف', 'طلاب', 'مقرئين', 'محتوى', 'فقه', 'جودة'], en: ['supervisor', 'students', 'readers', 'content', 'fiqh', 'quality'] }, productRoutes: ['/admin/supervisor-tasks', '/admin/supervisors', '/academy/supervisor'],
    sections: [
      { id: 'scope', title: { ar: 'اعرف نطاق صلاحيتك', en: 'Know your permission scope' }, steps: { ar: ['افتح لوحة الإشراف وراجع الأقسام الظاهرة لك فقط.', 'مشرف الطلاب يتابع الطلاب والطلبات والتقدم ضمن نطاقه.', 'مشرف المقرئين يتابع الطلبات والأداء والتوزيع ضمن نطاقه.', 'مشرف المحتوى يراجع المواد، ومشرف الفقه يتابع الأسئلة، ومشرف الجودة يراجع الالتزام والجودة.', 'المشرف العام ينسق المهام التي فوّضتها الإدارة دون أن يحل محل المدير العام.'], en: ['Open the supervisor dashboard and use only the sections visible to you.', 'Student supervisors track students, requests, and progress in scope.', 'Reader supervisors track applications, performance, and assignments in scope.', 'Content, fiqh, and quality supervisors review their respective queues.', 'General supervisors coordinate delegated work without replacing the general administrator.'] } },
      { id: 'workflow', title: { ar: 'نفّذ مهمة مراجعة', en: 'Complete a review task' }, steps: { ar: ['افتح المهام أو قائمة المراجعة الخاصة بتخصصك.', 'تحقق من صاحب الطلب والبيانات والحالة الحالية.', 'أضف ملاحظة واضحة واختر القرار المتاح وفق السياسة.', 'أكد الإجراء ثم راقب انتقال الحالة أو عودتها لصاحب الطلب.'], en: ['Open tasks or the review queue for your specialty.', 'Verify the requester, details, and current status.', 'Add a clear note and select an allowed decision.', 'Confirm and verify that the status moves to the next owner.'] }, note: { ar: 'عدم ظهور زر أو قسم يعني غالبًا أنه خارج رتبتك أو نطاقك، ولا ينبغي استخدام حساب رتبة أخرى.', en: 'A missing action usually means it is outside your role or scope; do not use another role’s account.' } },
    ],
  },
  {
    slug: 'admin-guide', group: 'admin', icon: 'admin', reviewedAt: '2026-07-21',
    title: { ar: 'المرجع التشغيلي الكامل للإدارة', en: 'Complete administration operations manual' },
    description: { ar: 'مرجع تفصيلي لعمل المدير العام ومدير المقرأة ومدير الأكاديمية: المستخدمون والصلاحيات والطلبات والتشغيل التعليمي والمحتوى والحوكمة.', en: 'A detailed manual for Super, Maqraa, and Academy administrators: users, permissions, applications, learning operations, content, and governance.' },
    audience: { ar: 'المدير العام ومدير المقرأة ومدير الأكاديمية ومن يُفوّض بمهام إدارية', en: 'Super Admin, Maqraa Admin, Academy Admin, and delegated administrators' },
    keywords: { ar: ['ادمن', 'مدير عام', 'مدير المقرأة', 'مدير الأكاديمية', 'مستخدمين', 'صلاحيات', 'طلبات', 'حلقات', 'تلاوات', 'دورات', 'تقارير', 'إعدادات', 'نسخ احتياطي', 'أمان'], en: ['admin', 'super admin', 'maqraa admin', 'academy admin', 'users', 'roles', 'applications', 'halaqat', 'recitations', 'courses', 'reports', 'settings', 'backup', 'security'] },
    productRoutes: ['/admin', '/admin/users', '/admin/role-management', '/admin/readers', '/admin/reader-applications', '/admin/recitations', '/admin/halaqat', '/academy/admin', '/academy/admin/courses', '/academy/admin/teachers', '/admin/reports', '/admin/settings'],
    sections: [
      { id: 'before-you-start', title: { ar: 'قبل تنفيذ أي إجراء إداري', en: 'Before any administrative action' }, intro: { ar: 'الإدارة تتعامل مع حسابات ومحتوى وقرارات تؤثر فورًا على المستخدمين، لذلك ابدأ دائمًا من التحقق لا من التعديل.', en: 'Administration affects accounts, content, and live user access, so always verify before changing anything.' }, steps: { ar: ['تأكد من اسم الحساب الذي دخلت به، ورتبته، ووضع الإدارة النشط الظاهر في الشريط الجانبي.', 'حدّد نطاق العملية: هل تخص المنصة كلها، المقرأة، أم الأكاديمية؟ لا تستخدم نطاقًا أوسع من المطلوب.', 'ابحث عن السجل بالاسم والبريد والمعرّف عند توفره، وراجع حالته الحالية وسجل نشاطه قبل اتخاذ القرار.', 'اقرأ رسائل التأكيد بعناية، خصوصًا عند التعطيل والحذف وتغيير الدور وإعادة ضبط الإعدادات.', 'اكتب سببًا واضحًا في الملاحظات عند الموافقة أو الرفض أو التصعيد؛ السبب جزء من التاريخ التشغيلي وليس رسالة شكلية.', 'بعد الحفظ، أعد فتح السجل أو راجع سجل التدقيق للتأكد أن التغيير المطلوب فقط هو الذي نُفّذ.'], en: ['Confirm the signed-in account, its rank, and the active administration mode shown in navigation.', 'Identify scope: platform-wide, Maqraa, or Academy. Never use broader authority than required.', 'Find the record by name, email, and ID where available; inspect status and history before deciding.', 'Read confirmation messages carefully, especially for suspension, deletion, role changes, and resets.', 'Record a clear reason for approvals, rejections, and escalations; it is part of the operational history.', 'After saving, reopen the record or inspect the audit trail to verify only the intended change occurred.'] }, note: { ar: 'لا تشارك حساب الإدارة، ولا تنفّذ إجراءات حساسة من جهاز عام أو جلسة دخول غير موثوقة.', en: 'Never share an administrator account or perform sensitive actions from a public or untrusted device.' } },
      { id: 'ranks-and-modes', title: { ar: 'الرتب الإدارية ومبدّل أوضاع المدير العام', en: 'Administrative ranks and Super Admin modes' }, steps: { ar: ['المدير العام يملك الحوكمة العامة، ويجمع صلاحيات المقرأة والأكاديمية، ويصل إلى هوية الموقع وSEO والتصميم والأدوار والأمان والنسخ الاحتياطي.', 'مدير المقرأة يدير جانب القرآن: المقرئون وطلبات انضمامهم والتلاوات والحلقات والحجوزات ومسارات الحفظ والتجويد ومسابقات وشهادات المقرأة.', 'مدير الأكاديمية يدير جانب التعليم: الطلاب والمعلمون وطلباتهم والدورات والدروس والتصنيفات والمسارات التعليمية والحلقات الأكاديمية والمحتوى والنتائج.', 'المشرف ليس مديرًا عامًا؛ تظهر له قوائم محددة مرتبطة بتخصصه ولا يحق له تجاوزها بكتابة رابط يدوي.', 'يستطيع المدير العام التبديل بين وضع المدير العام ووضع المقرأة ووضع الأكاديمية. الوضع يغيّر سياق القوائم والعمل اليومي ولا يلغي رتبته الأصلية.', 'قبل أي عملية جماعية أو تغيير إعداد، اقرأ اسم الوضع الحالي. إذا كنت تدير دورة فانتقل لوضع الأكاديمية، وإذا كنت تدير تلاوة أو مقرئًا فانتقل لوضع المقرأة.', 'المسارات الخاصة بالحوكمة مثل الصفحة الرئيسية وSEO والتصميم والهوية والأدوار والأمان والنسخ الاحتياطي تظل حصرية للمدير العام.'], en: ['Super Admin owns platform governance, includes Maqraa and Academy authority, and can access site identity, SEO, theme, roles, security, and backups.', 'Maqraa Admin manages Quran operations: readers, applications, recitations, halaqat, bookings, memorization and tajweed paths, competitions, and certificates.', 'Academy Admin manages education operations: students, teachers, applications, courses, lessons, categories, learning paths, academy halaqat, content, and outcomes.', 'A supervisor is not a Super Admin; only specialty-specific menus are available and direct URL entry does not extend authority.', 'Super Admin can switch among Super, Maqraa, and Academy modes. The mode changes working context, not the underlying rank.', 'Check the active mode before bulk work or settings changes. Use Academy for courses and Maqraa for readers or recitations.', 'Governance routes such as homepage, SEO, theme, branding, roles, security, and backup remain Super-Admin-only.'] } },
      { id: 'dashboard-routine', title: { ar: 'روتين بداية اليوم من لوحة الإدارة', en: 'Start-of-day dashboard routine' }, steps: { ar: ['راجع مؤشرات لوحة التحكم والتنبيهات لمعرفة الطلبات المعلقة والجلسات والأنشطة التي تحتاج تدخلًا.', 'ابدأ بطوابير الاعتماد القديمة أو الحالات المتأخرة، ثم راجع عمليات اليوم مثل الحلقات والجلسات والحجوزات.', 'افتح الإشعارات والإعلانات والرسائل الواردة وتأكد من عدم وجود مشكلة تشغيلية عامة.', 'راجع المهام المسندة للمشرفين بدل تنفيذ كل شيء بنفسك، وصعّد فقط الحالات التي تحتاج صلاحية أعلى.', 'استخدم التقارير لرصد تغير غير طبيعي في التسجيل أو النشاط أو الإنجاز، ثم انتقل إلى السجلات التفصيلية للتحقق.', 'في نهاية الجولة سجّل القرارات المهمة وتأكد من عدم بقاء نافذة تعديل أو مسودة غير محفوظة.'], en: ['Review dashboard indicators and alerts for pending applications, sessions, and activities needing intervention.', 'Start with the oldest or overdue approval queues, then inspect today’s halaqat, sessions, and bookings.', 'Check notifications, announcements, and incoming messages for platform-wide operational issues.', 'Review delegated supervisor tasks rather than handling everything personally; escalate only when higher authority is required.', 'Use reports to spot unusual changes in registration, activity, or completion, then verify through detailed records.', 'At the end of the round, document important decisions and ensure no edit form or draft remains unsaved.'] } },
      { id: 'user-directory', title: { ar: 'إدارة دليل المستخدمين والحسابات', en: 'Manage users and accounts' }, steps: { ar: ['افتح المستخدمين، ثم اختر التبويب المناسب أو استخدم البحث بالاسم أو البريد، ويمكن تضييق النتائج بالحالة والجنس والصفحات.', 'افتح ملف المستخدم قبل أي إجراء؛ راجع بياناته، دوره الأساسي، حالته، تاريخ انضمامه، وصول القرآن، وصول الأكاديمية، وتفضيل المنصة.', 'لإنشاء حساب إداريًا، أدخل الاسم والبريد وكلمة المرور والدور المطلوب بدقة، ثم راجع الحساب الجديد بعد إنشائه.', 'لتعديل البيانات، استخدم نموذج التعديل ولا تغيّر البريد أو الدور كحل لمشكلة وصول قبل التحقق من سببها الحقيقي.', 'التعطيل يمنع الحساب من الاستمرار في الاستخدام ويُفضّل على الحذف عند المخالفات المؤقتة أو التحقيقات. أعد التفعيل فقط بعد توثيق السبب.', 'يمكن ضبط وصول القرآن ووصول الأكاديمية وتفضيل المنصة من ملف المستخدم؛ هذه مفاتيح وصول مستقلة عن اسم الدور وقد تؤثر فورًا.', 'استخدم زر المحادثة من ملف المستخدم إذا كانت المشكلة تحتاج تواصلًا، ولا تطلب كلمة مروره أو رمز التحقق.', 'الحذف النهائي غير قابل للتراجع وقد يؤثر على بيانات مترابطة؛ استخدمه فقط وفق سياسة المؤسسة وبعد التأكد من الهوية والسجلات المطلوبة.', 'بعد تعديل الوصول، اطلب من المستخدم تسجيل الدخول مجددًا إذا لزم، ثم تحقق أن اللوحة الصحيحة أصبحت متاحة.'], en: ['Open Users, choose the relevant tab, or search by name/email; narrow results by status, gender, and pagination.', 'Open the user profile before acting; review identity, primary role, status, join date, Quran access, Academy access, and platform preference.', 'To create an account administratively, enter name, email, password, and role accurately, then inspect the new profile.', 'Use the edit form for profile changes; do not change email or role as a shortcut before diagnosing an access problem.', 'Suspension is preferable to deletion for temporary violations or investigations. Reactivate only after recording the reason.', 'Quran access, Academy access, and platform preference are independent controls and may take effect immediately.', 'Use the profile conversation action when communication is needed; never request passwords or verification codes.', 'Permanent deletion cannot be undone and may affect related records; use it only under policy after confirming identity and retention needs.', 'After access changes, ask the user to sign in again if needed and confirm the correct dashboard is available.'] }, note: { ar: 'تغيير الدور لا يساوي تلقائيًا منح كل مفاتيح الوصول؛ راجع الدور الأساسي والأدوار الإضافية ووصول القرآن والأكاديمية معًا.', en: 'Changing a role does not automatically equal every access flag; review primary role, additional roles, Quran access, and Academy access together.' } },
      { id: 'roles-permissions', title: { ar: 'تعيين الأدوار والصلاحيات الإضافية', en: 'Assign roles and additional permissions' }, steps: { ar: ['افتح إدارة الأدوار لفهم كتالوج الرتب وما تسمح به كل رتبة قبل التعيين.', 'من ملف المستخدم افتح شاشة الأدوار، ثم راجع دوره الأساسي وأدوار الأكاديمية الإضافية الحالية.', 'الأدوار الأساسية القابلة للتعيين إداريًا تشمل المدير العام ومدير المقرأة ومدير الأكاديمية ومشرف الطلاب ومشرف المقرئين وفق صلاحيتك.', 'يمكن منح أدوار أكاديمية إضافية مثل مدير المقرأة أو مدير الأكاديمية أو معلم أو مشرف محتوى أو فقه أو جودة أو مشرف عام.', 'امنح أقل قدر من الصلاحيات يكفي للعمل. لا تمنح دور مدير عام لمجرد أن المستخدم يحتاج شاشة واحدة.', 'تجنب جمع أدوار متعارضة دون حاجة تشغيلية واضحة، وسجّل صاحب الموافقة وسبب التغيير.', 'بعد الحفظ اختبر ظهور القوائم المطلوبة وعدم ظهور القوائم الحساسة، وراجع سجل التدقيق.', 'عند سحب صلاحية، راجع المهام المفتوحة التي كانت مسندة للمستخدم وأعد توزيعها حتى لا تتوقف العمليات.'], en: ['Open Role Management to understand the role catalogue and each rank before assigning anything.', 'From a user profile, open Roles and inspect the current primary role and additional Academy roles.', 'Assignable primary roles include Super Admin, Maqraa Admin, Academy Admin, Student Supervisor, and Reciter Supervisor subject to your authority.', 'Additional Academy roles may include Maqraa Admin, Academy Admin, Teacher, Content, Fiqh, Quality, or General Supervisor.', 'Apply least privilege. Never grant Super Admin merely to expose one screen.', 'Avoid conflicting combinations without a clear operational need, and record approver and reason.', 'After saving, verify required menus appear, sensitive menus remain hidden, and inspect the audit trail.', 'When revoking access, reassign the user’s open tasks so operations do not stall.'] } },
      { id: 'applications-invitations', title: { ar: 'طلبات المقرئين والمعلمين والدعوات', en: 'Reader and teacher applications and invitations' }, steps: { ar: ['راجع قائمة طلبات المقرئين أو طلبات المعلمين في نطاقها الصحيح، ورتب الطلبات حسب الحالة أو الأقدمية.', 'افتح الطلب كاملًا وتحقق من الاسم والبريد والتحقق والمعلومات المهنية والإجابات والمرفقات المتاحة.', 'قارن البيانات بمتطلبات القبول المعتمدة، ولا تعتمد الطلب من بطاقة القائمة وحدها.', 'إذا كانت البيانات ناقصة فاستخدم طلب الاستكمال عندما يكون متاحًا، وحدد المطلوب بدقة بدل الرفض المبهم.', 'عند القبول تأكد من الدور الذي سيُمنح، وحالة الحساب، ومفاتيح الوصول، ثم راقب انتقال المتقدم إلى لوحة الدور الصحيحة.', 'عند الرفض اكتب سببًا مهنيًا واضحًا يمكن فهمه، وتجنب تضمين معلومات داخلية أو بيانات متقدم آخر.', 'استخدم الدعوات لإنشاء مسار انضمام مضبوط للمستخدمين المطلوبين، وحدد الغرض والصلاحية وتابع القبول أو الانتهاء.', 'راجع الأسئلة المخصصة لطلبات الأكاديمية عند الحاجة، لكن لا تغيّر النموذج أثناء وجود حملة تقديم نشطة دون تنسيق.', 'بعد القرار تأكد من إرسال الإشعار وتحديث حالة الطلب والحساب معًا؛ اختلافهما يسبب بقاء المستخدم في شاشة الانتظار.'], en: ['Review Reader or Teacher Applications in the correct scope and order them by status or age.', 'Open the full application and verify identity, email verification, professional details, answers, and attachments.', 'Compare against approved acceptance criteria; never approve from the list card alone.', 'If incomplete, request specific missing information where supported instead of issuing a vague rejection.', 'On approval, confirm granted role, account status, and access flags, then verify routing to the correct dashboard.', 'On rejection, provide a professional, understandable reason without exposing internal or third-party information.', 'Use invitations for controlled onboarding; define purpose and validity and track acceptance or expiry.', 'Manage Academy application questions carefully and avoid changing a live campaign form without coordination.', 'After a decision, confirm notification, application state, and account state all update together.'] } },
      { id: 'maqraa-readers', title: { ar: 'إدارة المقرئين والمشرفين في المقرأة', en: 'Manage Maqraa readers and supervisors' }, steps: { ar: ['افتح المقرئين لمراجعة القائمة والحالة والتوفر والبيانات المرتبطة بكل مقرئ.', 'افتح ملف المقرئ قبل إسناد طلاب أو حلقات، وراجع اعتماده وأداءه وجدوله وحجم التكليف الحالي.', 'وزّع العمل بعدالة وفق التخصص والتوفر وعدد الطلاب والتلاوات المعلقة، وليس وفق ترتيب القائمة فقط.', 'استخدم إدارة المشرفين لتحديد المسؤوليات والمتابعة، ثم راجع مهام المشرفين المتأخرة بانتظام.', 'إذا توقف مقرئ مؤقتًا، أوقف الإسناد الجديد أولًا ثم انقل الجلسات والتلاوات المفتوحة قبل تعطيل الحساب.', 'عند وجود شكوى راجع التلاوة أو الجلسة والسجلات والمراسلات ذات الصلة قبل اتخاذ إجراء على الحساب.', 'تابع مؤشرات التأخير وجودة الملاحظات وتكرار إعادة التلاوة، ثم وجّه أو أعد توزيع العمل عند الحاجة.'], en: ['Open Readers to review roster, status, availability, and related details.', 'Inspect a reader profile before assigning students or halaqat; review approval, performance, schedule, and current load.', 'Distribute work fairly by specialty, availability, student count, and pending recitations—not list order alone.', 'Use Supervisor Management to define responsibilities, then review overdue supervisor tasks regularly.', 'If a reader pauses, stop new assignments first and transfer open sessions and recitations before suspension.', 'For complaints, inspect the relevant recitation/session, logs, and messages before acting on the account.', 'Track delays, feedback quality, and repeated retries, then coach or redistribute work as needed.'] } },
      { id: 'recitations-bookings', title: { ar: 'متابعة التلاوات والحجوزات والجلسات', en: 'Monitor recitations, bookings, and sessions' }, steps: { ar: ['استخدم التلاوات لمراجعة الحالات المعلقة والمقيّمة والتي تحتاج جلسة، وافتح التفاصيل للاستماع وقراءة تقييم المقرئ.', 'تحقق من السورة ونطاق الآيات والطالب والمقرئ والحالة قبل تعديل الإسناد أو النتيجة.', 'راقب زمن الانتظار والتلاوات غير المسندة، ثم أعد الإسناد عند غياب المقرئ أو تراكم قائمته.', 'من الحجوزات راجع الطالب والمقرئ والموعد والحالة، وعالج التعارضات قبل وقت الجلسة.', 'لا تعدّل نتيجة تعليمية مكتملة دون سبب موثق ومراجعة صاحب التقييم أو المشرف المسؤول.', 'في إعدادات الفيديو راجع إعدادات البث والجلسات، وافتح تفاصيل الجلسة عند وجود مشكلة دخول أو اتصال.', 'بعد الجلسة تأكد من تسجيل الحضور والنتيجة والملاحظات وتحديث تقدم الطالب، ولا تترك جلسة منتهية بحالة نشطة.', 'عند الإلغاء أو إعادة الجدولة، أخطر الأطراف وحدّث الموعد في النظام حتى لا تصلهم روابط أو تنبيهات قديمة.'], en: ['Use Recitations to review pending, assessed, and session-required items; open details to listen and inspect reader feedback.', 'Verify surah, verse range, student, reader, and state before changing assignment or outcome.', 'Monitor waiting time and unassigned recitations; reassign when a reader is absent or overloaded.', 'In Bookings, verify student, reader, time, and status, and resolve conflicts before the session.', 'Do not alter a completed educational result without a documented reason and review by the assessor or supervisor.', 'Use Video Settings and session details when diagnosing room access or connection issues.', 'After a session, confirm attendance, outcome, notes, and student progress; do not leave ended sessions active.', 'For cancellations or rescheduling, notify participants and update the system to prevent stale links or reminders.'] } },
      { id: 'halaqat-paths', title: { ar: 'إدارة الحلقات ومسارات الحفظ والتجويد', en: 'Manage halaqat, memorization, and tajweed paths' }, steps: { ar: ['أنشئ الحلقة ببيانات واضحة: الاسم والنوع والمقرئ والسعة والجدول والحالة وشروط الانضمام.', 'قبل إضافة الطلاب تحقق من السعة وتعارض المواعيد وملاءمة مستوى الطالب للحلقة.', 'افتح صفحة الحلقة لمراجعة الأعضاء والجلسات والحضور والتقدم، واستخدم الغرفة المباشرة في وقتها فقط.', 'عند تغيير المقرئ، راجع جدول المقرئ الجديد وأخبر الطلاب وانقل المسؤوليات المفتوحة.', 'في مسارات الحفظ عرّف المراحل وترتيبها ومتطلبات الانتقال، ثم راجع تقدم الطلاب والحالات الاستثنائية.', 'في مسارات التجويد حافظ على ترتيب المستويات والدروس ومعايير الإتقان، ولا تغيّر معيارًا بأثر رجعي دون مراجعة النتائج القديمة.', 'أغلق أو أرشف الحلقة المنتهية بدل حذف تاريخها التعليمي، وتأكد من اكتمال الحضور والتقييمات قبل الإغلاق.', 'راجع الحلقات قليلة الحضور أو الممتلئة باستمرار لاتخاذ قرار دمج أو فتح سعة جديدة.'], en: ['Create each halaqa with a clear name, type, reader, capacity, schedule, status, and joining rules.', 'Before adding students, verify capacity, schedule conflicts, and student level.', 'Use the halaqa page to review members, sessions, attendance, and progress; open the live room only at the scheduled time.', 'When replacing a reader, verify the new schedule, notify students, and transfer open responsibilities.', 'For memorization paths, define ordered stages and transition requirements, then review student progress and exceptions.', 'For tajweed paths, preserve level/lesson order and mastery criteria; do not retroactively change standards without reviewing past results.', 'Close or archive completed halaqat instead of deleting educational history, after attendance and assessments are complete.', 'Review chronically low-attendance or full halaqat to merge groups or add capacity.'] } },
      { id: 'academy-operations', title: { ar: 'إدارة الأكاديمية: الطلاب والمعلمون والدورات', en: 'Academy operations: students, teachers, and courses' }, steps: { ar: ['ابدأ من لوحة الأكاديمية وراجع الطلاب والمعلمين وطلبات المعلمين ومؤشرات الدورات النشطة.', 'في الطلاب راجع الوصول الأكاديمي والتسجيلات والتقدم، وعالج مشكلة الوصول من سببها بدل تسجيل الطالب يدويًا بلا تحقق.', 'في المعلمين راجع الحالة والدورات المسندة والحمل الحالي قبل إسناد دورة أو حلقة جديدة.', 'في الدورات راجع العنوان والوصف والتصنيف والمعلم والحالة والنشر والسعة أو شروط الالتحاق قبل إتاحتها.', 'افتح تفاصيل الدورة لإدارة المحتوى والطلاب والنتائج، واستخدم الأرشيف للدورات القديمة بدل إبقائها ضمن التشغيل اليومي.', 'نظّم التصنيفات والسلاسل والمسارات التعليمية قبل إضافة عدد كبير من الدورات حتى يبقى الاستعراض واضحًا.', 'راجع الدروس العامة والمحتوى المنشور للزوار، وتأكد أن المادة المسموح بها فقط هي المتاحة دون تسجيل.', 'تابع الحلقات الأكاديمية والجلسات والحضور بنفس قواعد الجدولة والإغلاق والتوثيق.', 'استخدم التحكم في الوصول عند الحاجة لمنح أو سحب دخول الأكاديمية، ثم تحقق من أثره على تجربة المستخدم.', 'راجع التحليلات والنتائج ومعدلات الإكمال لتحديد الدورات المتعثرة أو المحتوى الذي يحتاج تحديثًا.'], en: ['Start from the Academy dashboard and review students, teachers, teacher applications, and active-course indicators.', 'For students, inspect Academy access, enrollments, and progress; fix the cause rather than manually enrolling without verification.', 'For teachers, review status, assigned courses, and current workload before new assignments.', 'For courses, verify title, description, category, teacher, state, publication, capacity, and enrollment rules before release.', 'Open course details to manage content, students, and outcomes; archive old courses instead of leaving them in daily operations.', 'Organize categories, series, and learning paths before adding many courses so discovery stays clear.', 'Review public lessons and visitor-facing content to ensure only intended material is available without sign-in.', 'Operate Academy halaqat and sessions with the same scheduling, closure, attendance, and documentation discipline.', 'Use Access Control to grant or revoke Academy entry, then verify the user experience.', 'Review analytics, outcomes, and completion rates to identify struggling courses or stale content.'] } },
      { id: 'engagement', title: { ar: 'المسابقات والنقاط والشارات والشهادات', en: 'Competitions, points, badges, and certificates' }, steps: { ar: ['أنشئ المسابقة في النطاق الصحيح وحدد الاسم والوصف والفترة وشروط الاشتراك ومعايير الترتيب والجوائز بوضوح.', 'راجع المشاركات والنتائج قبل إعلان الفائزين، وتأكد من تطبيق معيار واحد على الجميع.', 'استخدم النقاط والشارات كقواعد تحفيز مفهومة؛ تجنب منح نقاط يدوية بلا سبب مسجل.', 'راجع لوحة الصدارة بعد أي تعديل نقاط للتأكد من عدم ظهور ترتيب غير مقصود.', 'في الشهادات تحقق من أهلية الطالب والاسم والدورة أو المسار وتاريخ الإنجاز قبل الإصدار.', 'صحّح البيانات المصدر أولًا إذا كان اسم الشهادة أو الإنجاز خاطئًا، ثم أعد الإصدار بدل تعديل ملف نهائي فقط.', 'أغلق المسابقة بعد انتهاء النتائج واحفظ تاريخها، ولا تحذفها إذا كانت مرتبطة بشهادات أو نقاط.', 'افصل مسابقات المقرأة عن مسابقات الأكاديمية عند اختلاف الشروط والجمهور والتقارير.'], en: ['Create competitions in the correct scope with clear name, description, period, eligibility, ranking criteria, and rewards.', 'Review submissions and results before announcing winners, applying one standard to everyone.', 'Use points and badges as understandable incentive rules; avoid unexplained manual awards.', 'Inspect the leaderboard after point changes for unintended ranking effects.', 'Before issuing certificates, verify eligibility, learner name, course/path, and completion date.', 'If certificate data is wrong, correct the source record first, then reissue rather than editing only the final file.', 'Close competitions after results and preserve their history; do not delete records linked to certificates or points.', 'Keep Maqraa and Academy competitions separate when audience, rules, or reporting differ.'] } },
      { id: 'communications', title: { ar: 'الإشعارات والإعلانات والمحادثات والرسائل', en: 'Notifications, announcements, conversations, and messages' }, steps: { ar: ['استخدم الإعلانات للمعلومات العامة وحدد الجمهور والنطاق ومدة الظهور قبل النشر.', 'راجع نص الإعلان في العربية والإنجليزية إن كان الجمهور ثنائي اللغة، وتأكد من وضوح التاريخ والرابط والإجراء المطلوب.', 'استخدم الإشعارات للتنبيهات الموجهة، وتجنب إرسال إشعار جماعي لا يحتاجه معظم المستخدمين.', 'راجع المحادثات للمتابعة والدعم، واحفظ التواصل داخل القناة المخصصة بدل نقله إلى حسابات شخصية.', 'تعامل مع رسائل التواصل حسب الأولوية، واربط الرد بالمشكلة الفعلية ثم أغلق الحالة بعد التأكد من الحل.', 'عدّل قوالب البريد بحذر؛ اختبر المتغيرات والروابط والاتجاه واللغة قبل اعتماد القالب.', 'لا ترسل بيانات حساسة أو كلمات مرور أو رموز تحقق داخل إعلان أو محادثة أو بريد.', 'عند وقوع عطل عام، انشر رسالة موحدة ومحددة ثم حدّثها عند الحل بدل إرسال رسائل متعارضة.'], en: ['Use announcements for broad information and define audience, scope, and display period before publishing.', 'Review Arabic and English copy for bilingual audiences and make dates, links, and required actions explicit.', 'Use notifications for targeted alerts; avoid mass alerts irrelevant to most users.', 'Use platform conversations for support and keep operational communication out of personal accounts.', 'Prioritize contact messages, tie each response to the actual issue, and close only after confirming resolution.', 'Edit email templates carefully; test variables, links, direction, and language before activation.', 'Never send sensitive data, passwords, or verification codes through announcements, chat, or email.', 'For a widespread incident, publish one consistent status message and update it on resolution.'] } },
      { id: 'content-community', title: { ar: 'المكتبة والفقه والمنتدى والمحتوى', en: 'Library, fiqh, community, and content' }, steps: { ar: ['في مكتبة الكتب راجع العنوان والمؤلف والوصف والتصنيف والغلاف والملفات قبل الحفظ أو النشر.', 'عند تعديل كتاب، راجع الملفات الحالية قبل حذف أي ملف وتأكد من وجود بديل صالح للمستخدمين.', 'في مكتبة الفقه راجع المادة والمرجع والتصنيف والمسؤولين عن المراجعة وفق سير العمل المتاح.', 'في المنتدى راقب البلاغات والمحتوى المخالف، واتخذ إجراءً متناسبًا مع توثيق السبب.', 'لا تحذف نقاشًا كاملًا بسبب مشاركة واحدة إذا كان يمكن معالجة المخالفة وحدها وفق السياسة.', 'راجع الصفحات الثابتة مثل الشروط والخصوصية والمحتوى التعريفي بعد أي تعديل، بالعربية والإنجليزية وعلى الهاتف.', 'افصل المراجعة العلمية عن المراجعة التقنية: اعتماد صحة المادة لا يغني عن فحص الروابط والتنسيق والوصول.', 'عند سحب محتوى منشور، حدد هل سيُخفى مؤقتًا أم يُؤرشف أم يُحذف، وافحص الروابط التي كانت تشير إليه.'], en: ['For library books, verify title, author, description, category, cover, and files before saving or publishing.', 'When editing a book, inspect existing files before deletion and ensure users retain a valid replacement.', 'For fiqh content, review material, source, category, and assigned reviewers according to the available workflow.', 'Moderate reports and violations proportionately and document the reason.', 'Do not remove an entire discussion for one post if policy allows handling only the violation.', 'Review static pages such as terms, privacy, and informational content in both languages and on mobile after changes.', 'Separate scholarly and technical review: content approval does not replace link, formatting, and access checks.', 'When withdrawing published content, choose hide, archive, or delete deliberately and inspect inbound links.'] } },
      { id: 'public-site', title: { ar: 'الصفحة الرئيسية وSEO والتصميم والهوية', en: 'Homepage, SEO, theme, and branding' }, intro: { ar: 'هذا القسم للمدير العام فقط لأنه يؤثر على الموقع العام وكل الزوار.', en: 'This section is Super-Admin-only because it affects the public website and every visitor.' }, steps: { ar: ['في محرر الصفحة الرئيسية راجع الأقسام وترتيبها ونصوصها وروابط الأزرار قبل الحفظ، ثم افتح الموقع العام للتحقق.', 'في SEO راجع عنوان ووصف الصفحات والبيانات المستخدمة في المشاركة ومحركات البحث، وتجنب التكرار أو الوعود غير الدقيقة.', 'في التصميم والألوان غيّر الرموز المعتمدة فقط، وافحص التباين والوضع الداكن والعربية والإنجليزية قبل الاعتماد.', 'استخدم استعادة القيم الافتراضية فقط بعد التأكد؛ قد تحفظ فورًا وتغيّر شكل الموقع بالكامل.', 'في الهوية البصرية راجع الشعار والاسم والعناصر المستخدمة في الواجهة والرسائل لضمان الاتساق.', 'في صفحات المحتوى الثابت حرر النسختين اللغويتين ولا تنشر ترجمة فارغة أو قديمة.', 'اختبر الصفحة الرئيسية ومسار التسجيل وتسجيل الدخول بعد أي تغيير كبير في الهوية أو القالب.', 'نسّق تغييرات العلامة وSEO مع الفريق المختص وسجّل ما تغير وموعد النشر لإمكانية المراجعة.'], en: ['In Homepage Editor, review section order, copy, and button links before saving, then verify the public site.', 'In SEO, review page titles, descriptions, and sharing/search metadata; avoid duplication or inaccurate promises.', 'In Theme, change approved tokens only and test contrast, dark mode, Arabic, and English.', 'Use Restore Defaults only intentionally; it may save immediately and alter the entire site.', 'In Branding, verify logo, name, and identity elements across interface and communications.', 'For static content pages, maintain both languages and never publish an empty or stale translation.', 'Test homepage, registration, and sign-in after major identity or theme changes.', 'Coordinate branding and SEO releases, recording what changed and when for review.'] }, note: { ar: 'لا تستخدم لوحة التصميم للتجربة على الموقع الحي؛ جهّز القيم واعتمدها ضمن نافذة تغيير معلنة.', en: 'Do not experiment with theme controls on the live site; prepare and approve values within a controlled change window.' } },
      { id: 'settings-security-backup', title: { ar: 'إعدادات المنصة والأمان والنسخ الاحتياطي', en: 'Platform settings, security, and backup' }, steps: { ar: ['افتح إعدادات النظام واقرأ وصف كل خيار ونطاقه قبل التغيير؛ بعض الإعدادات تؤثر على التسجيل أو الوصول أو الإشعارات فورًا.', 'غيّر خيارًا واحدًا في كل مرة عند استكشاف مشكلة، وسجّل القيمة السابقة والجديدة ووقت التغيير.', 'في الأمان راجع الضوابط والتنبيهات والجلسات وفق السياسة، ولا تخفّض الحماية لتجاوز مشكلة مستخدم واحد.', 'عند الاشتباه في حساب إداري، عطّله أو اسحب صلاحياته وفق إجراءات الحادث، ثم راجع السجلات ولا تحذف الدليل.', 'استخدم وضع الصيانة فقط عند وجود عمل معلن، وتأكد أن مسار دخول الإدارة سيظل متاحًا لإيقافه.', 'أنشئ النسخة الاحتياطية قبل التغييرات الكبرى وفق سياسة المؤسسة، وتحقق من اكتمالها وتاريخها بدل افتراض نجاحها.', 'النسخة الاحتياطية غير المختبرة ليست خطة استعادة؛ نفّذ اختبارات الاستعادة ضمن بيئة وإجراء معتمدين.', 'لا تنزّل نسخًا أو سجلات حساسة إلى أجهزة شخصية، ولا ترسلها عبر محادثات عادية.', 'بعد تغيير إعداد حساس اختبر حسابًا عاديًا وحسابًا إداريًا للتأكد من أن الوصول المقصود فقط ما زال يعمل.'], en: ['Read each system setting and its scope before changing it; some options immediately affect registration, access, or notifications.', 'When troubleshooting, change one setting at a time and record old/new values and timestamp.', 'In Security, follow policy for controls, alerts, and sessions; never weaken protection to solve one user’s issue.', 'For a suspected admin account, suspend or revoke access under incident procedure, inspect logs, and preserve evidence.', 'Use maintenance mode only for announced work and ensure administrators can still enter to disable it.', 'Create backups before major changes under policy and verify completion and timestamp.', 'An untested backup is not a recovery plan; perform approved restore testing in the proper environment.', 'Never download sensitive backups or logs to personal devices or send them through ordinary chat.', 'After sensitive settings changes, test both normal-user and admin access to verify intended boundaries.'] } },
      { id: 'reports-audit', title: { ar: 'التقارير والتحليلات وسجلات التدقيق', en: 'Reports, analytics, and audit trails' }, steps: { ar: ['ابدأ بسؤال تشغيلي واضح قبل فتح التقرير: ما الذي تريد قياسه، ولأي فترة، وفي أي نطاق؟', 'استخدم الفلاتر والتواريخ نفسها عند مقارنة فترتين، ولا تقارن رقمًا إجماليًا بنسبة أو نطاقًا عامًا بقسم واحد.', 'انتقل من المؤشر الإجمالي إلى السجلات التفصيلية قبل اتخاذ قرار على مستخدم أو معلم أو مقرئ.', 'راجع سجل النشاط للأحداث اليومية وسجل التدقيق الموحد للتغييرات الحساسة مثل الأدوار والوصول والإعدادات.', 'عند التحقيق دوّن وقت الحدث وصاحب الإجراء والسجل المتأثر والقيمة السابقة والجديدة إن ظهرت.', 'لا تعدّل بيانات لإخفاء خطأ تشغيلي؛ صحح السبب واترك سجل القرار والمراجعة واضحًا.', 'صدّر أو شارك أقل قدر لازم من البيانات، وأخفِ البيانات الشخصية عندما لا تكون مطلوبة للغرض.', 'استخدم النتائج لتحسين التوزيع والمحتوى والدعم، وليس لمعاقبة شخص بناءً على مؤشر منفرد خارج سياقه.'], en: ['Start with a clear operational question: what metric, period, and scope are needed?', 'Use matching filters and dates when comparing periods; do not compare totals to rates or global scope to one department.', 'Drill from aggregate indicators into detailed records before acting on a user, teacher, or reader.', 'Use activity logs for daily events and the unified audit log for sensitive role, access, and settings changes.', 'For investigations, record event time, actor, affected record, and previous/new values where available.', 'Never alter data to hide an operational mistake; correct the cause and preserve decision and review history.', 'Export or share only necessary data and remove personal information when it is not required.', 'Use findings to improve staffing, content, and support—not to penalize someone from one context-free metric.'] } },
      { id: 'incident-playbook', title: { ar: 'التعامل مع الأعطال والشكاوى والحوادث', en: 'Incident, complaint, and outage playbook' }, steps: { ar: ['حدّد هل المشكلة فردية أم عامة: حساب واحد، دور كامل، خدمة الجلسات، الدفع، البريد، أم الموقع كله.', 'سجّل وقت البداية والصفحة والخطوات ورسالة الخطأ والحسابات المتأثرة دون نسخ كلمات مرور أو رموز تحقق.', 'افحص آخر تغييرات في الإعدادات والأدوار والمحتوى وسجل التدقيق قبل تنفيذ تعديل جديد.', 'إذا كانت المشكلة عامة، قلّل التغييرات المتزامنة، انشر إعلان حالة واضحًا، وحدد مسؤول متابعة واحدًا.', 'إذا تعلقت بصلاحية، قارن الحساب المتأثر بحساب سليم من الدور نفسه: الدور الأساسي والأدوار الإضافية ومفاتيح الوصول والحالة.', 'إذا تعلقت بجلسة، افحص الموعد والحالة والمشاركين وإعدادات الفيديو والاتصال قبل إعادة إنشائها.', 'لا تحذف السجل المتأثر كحل سريع؛ احتفظ بالأدلة وصعّد للمسؤول التقني عند الحاجة.', 'بعد الحل اختبر المسار من بدايته بحساب مناسب، حدّث المتضررين، ثم وثّق السبب والإجراء الوقائي.'], en: ['Classify the issue: one account, an entire role, sessions, payments, email, or the whole site.', 'Record start time, page, reproduction steps, error, and affected accounts—never passwords or verification codes.', 'Inspect recent settings, role, and content changes plus audit logs before introducing another change.', 'For a broad incident, minimize simultaneous changes, publish a clear status message, and assign one coordinator.', 'For access incidents, compare against a healthy peer account: primary role, extra roles, access flags, and status.', 'For session incidents, inspect schedule, state, participants, video settings, and connectivity before recreating anything.', 'Do not delete the affected record as a quick fix; preserve evidence and escalate technically when required.', 'After resolution, test the full path with an appropriate account, update affected users, and document cause and prevention.'] } },
      { id: 'end-of-day', title: { ar: 'قائمة مراجعة نهاية اليوم الإداري', en: 'End-of-day administration checklist' }, steps: { ar: ['تأكد من معالجة الطلبات ذات الأولوية أو إسنادها لشخص محدد مع موعد متابعة.', 'راجع الجلسات المنتهية والحضور والتقييمات التي لم تُغلق بصورة صحيحة.', 'افحص التلاوات غير المسندة والحجوزات المتعارضة والحلقات التي ستبدأ في اليوم التالي.', 'راجع أي حساب عُطّل أو دور تغيّر اليوم وتأكد من وجود سبب وسجل واضح.', 'تأكد من حفظ مسودات الإعلانات والمحتوى أو إلغائها، وعدم نشر محتوى تجريبي.', 'راجع سجل التدقيق للتغييرات الحساسة التي نفذتها، وأبلغ عن أي نتيجة غير متوقعة فورًا.', 'سجّل المشكلات المفتوحة وحالة كل منها وصاحب المتابعة بدل تركها معتمدة على الذاكرة.', 'سجّل الخروج من حساب الإدارة وأغلق الجلسة على الأجهزة غير المخصصة لك.'], en: ['Ensure priority applications are completed or assigned to a named owner with a follow-up date.', 'Review ended sessions, attendance, and assessments that were not properly closed.', 'Check unassigned recitations, conflicting bookings, and tomorrow’s halaqat.', 'Review accounts suspended or roles changed today and confirm a clear reason and record.', 'Save or discard announcement/content drafts and ensure no test material is public.', 'Inspect audit entries for your sensitive changes and report unexpected outcomes immediately.', 'Record open issues, status, and owner instead of relying on memory.', 'Sign out of the administrator account and close sessions on devices not dedicated to you.'] } },
    ],
  },
  {
    slug: 'troubleshooting', group: 'support', icon: 'support', reviewedAt: '2026-07-21',
    title: { ar: 'حل المشكلات الشائعة', en: 'Troubleshooting' }, description: { ar: 'حل مشاكل الدخول، الموافقات، المحتوى، الجلسات ورفع الملفات.', en: 'Resolve sign-in, approval, content, session, and upload issues.' }, audience: { ar: 'جميع المستخدمين', en: 'All users' }, keywords: { ar: ['مشكلة', 'لا يعمل', 'انتظار', 'رفع', 'جلسة', 'دعم'], en: ['problem', 'not working', 'pending', 'upload', 'session', 'support'] }, productRoutes: ['/forgot-password', '/contact', '/faq'],
    sections: [
      { id: 'access', title: { ar: 'لا أستطيع الدخول أو رؤية القسم', en: 'I cannot sign in or see a section' }, steps: { ar: ['تأكد من البريد وكلمة المرور ومن إكمال التحقق.', 'استخدم استعادة كلمة المرور بدل تكرار المحاولات.', 'تحقق من أن طلب المعلم أو المقرئ قُبل وأن الحساب نشط.', 'إذا دخلت لكن قسمًا غير ظاهر، فغالبًا لا تملكه رتبتك أو لم يُمنح لك وصول الأكاديمية.'], en: ['Verify your email, password, and email confirmation.', 'Use password recovery instead of repeating failed attempts.', 'Check that your teacher or reader application is approved and the account active.', 'If a section is hidden, your role may not include it or academy access may not be enabled.'] } },
      { id: 'content-session', title: { ar: 'الدورة أو الجلسة أو الملف لا يعمل', en: 'A course, session, or file is unavailable' }, steps: { ar: ['حدّث الصفحة وتحقق من اتصالك ووقت الجلسة.', 'تأكد من قبول الالتحاق ونشر الدرس وعدم انتهاء الجلسة.', 'عند رفع ملف، استخدم النوع والحجم المطلوبين وانتظر اكتمال الرفع قبل الإرسال.', 'إذا استمرت المشكلة، أرسل للدعم اسم الصفحة والوقت ووصفًا دقيقًا للخطوات دون إرسال كلمة المرور.'], en: ['Refresh and check your connection and session time.', 'Confirm enrollment approval, lesson publication, and session status.', 'For uploads, use the required type and size and wait for completion.', 'If it continues, contact support with page name, time, and exact steps—never your password.'] } },
    ],
  },
]

export function getGuide(slug: string) {
  return docsGuides.find((guide) => guide.slug === slug)
}

export function getGuidesByGroup(group: DocsGuide['group']) {
  return docsGuides.filter((guide) => guide.group === group)
}
